#!/usr/bin/env Rscript
# Written by Noah Winters, Aug 2021
# This script chooses the longest nb-arc domain for genes that possess >1 
# It is intended as a support script for generate_nbarc_alignments.sh

suppressPackageStartupMessages(library("argparse"))
suppressPackageStartupMessages(library("tidyverse"))

# create parser object
parser <- ArgumentParser()

# specify our desired options 
# by default ArgumentParser will add an help option 
parser$add_argument("--domain_position_file", type = "character", default="None", 
                    help = "Tab-delimited file containing NB-ARC positions for each NLR, from classify_nlr.sh. [default %(default)s]")
parser$add_argument("--orthogroup_file", type = "character", default="None", 
                    help = "Tab-delimited orthogroup file like that generated by PlantTribes. Gene in one column, orthogroup assignment in the other. [default %(default)s]")

# Get command line options, if help option encountered print help and exit,
# Otherwise if options not found on command line then set defaults, 
args <- parser$parse_args()

# Make dplyr less noisy 
options(dplyr.summarise.inform = FALSE)

# Read in orthogroup_file
ortho <- read.table(args$orthogroup_file, header = TRUE, skip = 1, sep = '\t') %>%
  setNames(nm = c("Gene", "Orthogroup"))

# Choose longest NB-ARC domain
dom_pos <- read.table(args$domain_position_file,  header = FALSE, sep = ' ', skip = 1) %>%
  setNames(nm = c("Gene", "E.value", "Start", "Stop")) %>%
  inner_join(ortho, by = "Gene") %>% 
  mutate(Length = abs(Stop - Start)) %>%
  group_by(Gene) %>% 
  filter(Length == max(Length)) %>% # Choose longest domain
  distinct(., Gene, .keep_all = TRUE) %>% # If two domains are the same length, choose arbitrarily
  dplyr::select(c(Gene, Start, Stop, Orthogroup)) %>%
  mutate(Start = Start +1) %>% # Necessary because of seqtk indexing
  unite("ID", Gene:Start, sep = ":") %>%
  unite("ID", ID:Stop, sep = "-") %>%
  setNames(nm = c("Gene:Start-Stop", "Orthogroup"))

# Write output to stdout
cat(format_tsv(dom_pos, na = "none", escape = "none"))